In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import seaborn as sns
import plotly.express as px

In [2]:
df=pd.read_csv(r'C:\Users\asmit\Downloads\Algerian_forest_fires_dataset_UPDATE.csv',header=1)

In [3]:
df.head()

day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI  BUI  FWI  \
0  01    06  2012          29  57  18     0  65.7  3.4   7.6  1.3  3.4  0.5   
1  02    06  2012          29  61  13   1.3  64.4  4.1   7.6    1  3.9  0.4   
2  03    06  2012          26  82  22  13.1  47.1  2.5   7.1  0.3  2.7  0.1   
3  04    06  2012          25  89  13   2.5  28.6  1.3   6.9    0  1.7    0   
4  05    06  2012          27  77  16     0  64.8    3  14.2  1.2  3.9  0.5   

     Classes    
0  not fire     
1  not fire     
2  not fire     
3  not fire     
4  not fire

In [4]:
df.tail()

day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI   BUI  \
241  26    09  2012          30  65  14     0  85.4   16  44.5  4.5  16.9   
242  27    09  2012          28  87  15   4.4  41.1  6.5     8  0.1   6.2   
243  28    09  2012          27  87  29   0.5  45.9  3.5   7.9  0.4   3.4   
244  29    09  2012          24  54  18   0.1  79.7  4.3  15.2  1.7   5.1   
245  30    09  2012          24  64  15   0.2  67.3  3.8  16.5  1.2   4.8   

     FWI     Classes    
241  6.5       fire     
242    0   not fire     
243  0.2   not fire     
244  0.7   not fire     
245  0.5  not fire

In [5]:
#There is a need to drop rows 122 and 123 as it contains header row and reset the index value
df.drop(df.index[122:124],inplace=True)

df.reset_index()

index day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI  \
0        0  01    06  2012          29  57  18     0  65.7  3.4   7.6  1.3   
1        1  02    06  2012          29  61  13   1.3  64.4  4.1   7.6    1   
2        2  03    06  2012          26  82  22  13.1  47.1  2.5   7.1  0.3   
3        3  04    06  2012          25  89  13   2.5  28.6  1.3   6.9    0   
4        4  05    06  2012          27  77  16     0  64.8    3  14.2  1.2   
..     ...  ..   ...   ...         ...  ..  ..   ...   ...  ...   ...  ...   
239    241  26    09  2012          30  65  14     0  85.4   16  44.5  4.5   
240    242  27    09  2012          28  87  15   4.4  41.1  6.5     8  0.1   
241    243  28    09  2012          27  87  29   0.5  45.9  3.5   7.9  0.4   
242    244  29    09  2012          24  54  18   0.1  79.7  4.3  15.2  1.7   
243    245  30    09  2012          24  64  15   0.2  67.3  3.8  16.5  1.2   

      BUI  FWI     Classes    
0     3.4  0.5   not fire     
1     3.9  0.4   not fire     
2     2.7  0.1   not fire     
3     1.7    0   not fire     
4     3.9  0.5   not fire     
..    ...  ...           ...  
239  16.9  6.5       fire     
240   6.2    0   not fire     
241   3.4  0.2   not fire     
242   5.1  0.7   not fire     
243   4.8  0.5  not fire      

[244 rows x 15 columns]

In [6]:
df.dtypes

day            object
month          object
year           object
Temperature    object
 RH            object
 Ws            object
Rain           object
FFMC           object
DMC            object
DC             object
ISI            object
BUI            object
FWI            object
Classes        object
dtype: object

In [8]:
df.shape

(244, 14)

In [9]:
df.describe()
##Describe shows the count,unique,top and freq of dataset as all the columns are object here

day month  year Temperature   RH   Ws Rain   FFMC  DMC   DC  ISI  BUI  \
count   244   244   244         244  244  244   244   244  244  244  244  244   
unique   31     4     1          19   62   18    39   173  166  198  106  174   
top      25    07  2012          35   64   14     0  88.9  7.9    8  1.1    3   
freq      8    62   244          29   10   43   133     8    5    5    8    5   

        FWI Classes    
count   244       243  
unique  127         8  
top     0.4   fire     
freq     12       131

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 244 entries, 0 to 245
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   day          244 non-null    object
 1   month        244 non-null    object
 2   year         244 non-null    object
 3   Temperature  244 non-null    object
 4    RH          244 non-null    object
 5    Ws          244 non-null    object
 6   Rain         244 non-null    object
 7   FFMC         244 non-null    object
 8   DMC          244 non-null    object
 9   DC           244 non-null    object
 10  ISI          244 non-null    object
 11  BUI          244 non-null    object
 12  FWI          244 non-null    object
 13  Classes      243 non-null    object
dtypes: object(14)
memory usage: 28.6+ KB


In [11]:
#numerical and categorical columns

df_num=[features for features in df.columns if df[features].dtype !='O']
df_num

[]

In [12]:
df_cat=[features for features in df.columns if df[features].dtype=='O']
df_cat

['day',
 'month',
 'year',
 'Temperature',
 ' RH',
 ' Ws',
 'Rain ',
 'FFMC',
 'DMC',
 'DC',
 'ISI',
 'BUI',
 'FWI',
 'Classes  ']

In [13]:
#To check the null values
df.isnull().sum()

day            0
month          0
year           0
Temperature    0
 RH            0
 Ws            0
Rain           0
FFMC           0
DMC            0
DC             0
ISI            0
BUI            0
FWI            0
Classes        1
dtype: int64

In [14]:
df.nunique()

day             31
month            4
year             1
Temperature     19
 RH             62
 Ws             18
Rain            39
FFMC           173
DMC            166
DC             198
ISI            106
BUI            174
FWI            127
Classes          8
dtype: int64

In [15]:
df['Region']=0
df.head()
#We will convert the region as 1 for Bejaia Region Dataset and region as 0 for Sidi-Bel Abbes Region Dataset

day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI  BUI  FWI  \
0  01    06  2012          29  57  18     0  65.7  3.4   7.6  1.3  3.4  0.5   
1  02    06  2012          29  61  13   1.3  64.4  4.1   7.6    1  3.9  0.4   
2  03    06  2012          26  82  22  13.1  47.1  2.5   7.1  0.3  2.7  0.1   
3  04    06  2012          25  89  13   2.5  28.6  1.3   6.9    0  1.7    0   
4  05    06  2012          27  77  16     0  64.8    3  14.2  1.2  3.9  0.5   

     Classes    Region  
0  not fire          0  
1  not fire          0  
2  not fire          0  
3  not fire          0  
4  not fire          0

In [16]:
for i in range(len(df)):
    if i >=122:
        df['Region'].values[i]=1

In [17]:
df[115:130]

day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI   BUI  \
115  24    09  2012          29  65  19   0.6  68.3  5.5  15.2  1.5   5.8   
116  25    09  2012          26  81  21   5.8  48.6    3   7.7  0.4     3   
117  26    09  2012          31  54  11     0    82    6  16.3  2.5   6.2   
118  27    09  2012          31  66  11     0  85.7  8.3  24.9    4     9   
119  28    09  2012          32  47  14   0.7  77.5  7.1   8.8  1.8   6.8   
120  29    09  2012          26  80  16   1.8  47.4  2.9   7.7  0.3     3   
121  30    09  2012          25  78  14   1.4    45  1.9   7.5  0.2   2.4   
124  01    06  2012          32  71  12   0.7  57.1  2.5   8.2  0.6   2.8   
125  02    06  2012          30  73  13     4  55.7  2.7   7.8  0.6   2.9   
126  03    06  2012          29  80  14     2  48.7  2.2   7.6  0.3   2.6   
127  04    06  2012          30  64  14     0  79.4  5.2  15.4  2.2   5.6   
128  05    06  2012          32  60  14   0.2  77.1    6  17.6  1.8   6.5   
129  06    06  2012          35  54  11   0.1  83.7  8.4  26.3  3.1   9.3   
130  07    06  2012          35  44  17   0.2  85.6  9.9  28.9  5.4  10.7   
131  08    06  2012          28  51  17   1.3  71.4  7.7   7.4  1.5   7.3   

     FWI    Classes    Region  
115  0.7  not fire          0  
116  0.1  not fire          0  
117  1.7  not fire          0  
118  4.1      fire          0  
119  0.9  not fire          0  
120  0.1  not fire          0  
121  0.1  not fire          0  
124  0.2  not fire          1  
125  0.2  not fire          1  
126  0.1  not fire          1  
127    1  not fire          1  
128  0.9  not fire          1  
129  3.1      fire          1  
130    6      fire          1  
131  0.8  not fire          1

In [18]:
df["Classes  "].unique()

array(['not fire   ', 'fire   ', 'fire', 'fire ', 'not fire', 'not fire ',
       'not fire     ', nan, 'not fire    '], dtype=object)

In [19]:
df["Classes  "]=df["Classes  "].str.strip(" ")
df["Classes  "] =df["Classes  "].str.lstrip(" ")   


In [20]:
df["Classes  "].unique()

array(['not fire', 'fire', nan], dtype=object)

In [21]:
df.columns

Index(['day', 'month', 'year', 'Temperature', ' RH', ' Ws', 'Rain ', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes  ', 'Region'],
      dtype='object')

In [22]:
df.set_axis(['day', 'month', 'year', 'Temperature', ' RH', ' Ws', 'Rain ', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI','Classes  ','Region'], axis='columns')

day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI   BUI  \
0    01    06  2012          29  57  18     0  65.7  3.4   7.6  1.3   3.4   
1    02    06  2012          29  61  13   1.3  64.4  4.1   7.6    1   3.9   
2    03    06  2012          26  82  22  13.1  47.1  2.5   7.1  0.3   2.7   
3    04    06  2012          25  89  13   2.5  28.6  1.3   6.9    0   1.7   
4    05    06  2012          27  77  16     0  64.8    3  14.2  1.2   3.9   
..   ..   ...   ...         ...  ..  ..   ...   ...  ...   ...  ...   ...   
241  26    09  2012          30  65  14     0  85.4   16  44.5  4.5  16.9   
242  27    09  2012          28  87  15   4.4  41.1  6.5     8  0.1   6.2   
243  28    09  2012          27  87  29   0.5  45.9  3.5   7.9  0.4   3.4   
244  29    09  2012          24  54  18   0.1  79.7  4.3  15.2  1.7   5.1   
245  30    09  2012          24  64  15   0.2  67.3  3.8  16.5  1.2   4.8   

     FWI Classes    Region  
0    0.5  not fire       0  
1    0.4  not fire       0  
2    0.1  not fire       0  
3      0  not fire       0  
4    0.5  not fire       0  
..   ...       ...     ...  
241  6.5      fire       1  
242    0  not fire       1  
243  0.2  not fire       1  
244  0.7  not fire       1  
245  0.5  not fire       1  

[244 rows x 15 columns]

In [23]:
df.replace('14.6 9','14.7',inplace=True)

In [24]:
df.replace('not fire','notfire',inplace=True)
df

day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI   BUI  \
0    01    06  2012          29  57  18     0  65.7  3.4   7.6  1.3   3.4   
1    02    06  2012          29  61  13   1.3  64.4  4.1   7.6    1   3.9   
2    03    06  2012          26  82  22  13.1  47.1  2.5   7.1  0.3   2.7   
3    04    06  2012          25  89  13   2.5  28.6  1.3   6.9    0   1.7   
4    05    06  2012          27  77  16     0  64.8    3  14.2  1.2   3.9   
..   ..   ...   ...         ...  ..  ..   ...   ...  ...   ...  ...   ...   
241  26    09  2012          30  65  14     0  85.4   16  44.5  4.5  16.9   
242  27    09  2012          28  87  15   4.4  41.1  6.5     8  0.1   6.2   
243  28    09  2012          27  87  29   0.5  45.9  3.5   7.9  0.4   3.4   
244  29    09  2012          24  54  18   0.1  79.7  4.3  15.2  1.7   5.1   
245  30    09  2012          24  64  15   0.2  67.3  3.8  16.5  1.2   4.8   

     FWI Classes    Region  
0    0.5   notfire       0  
1    0.4   notfire       0  
2    0.1   notfire       0  
3      0   notfire       0  
4    0.5   notfire       0  
..   ...       ...     ...  
241  6.5      fire       1  
242    0   notfire       1  
243  0.2   notfire       1  
244  0.7   notfire       1  
245  0.5   notfire       1  

[244 rows x 15 columns]

In [25]:
convert_dict={'day':'int64','month':'int64', 'year':'int64', 'Temperature':'int64', ' RH':'int64', ' Ws':'int64', 'Rain ':'float64', 'FFMC':'float64',
       'DMC':'float64', 'DC':'float64', 'ISI':'float64', 'BUI':'float64',}
df=df.astype(convert_dict)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 244 entries, 0 to 245
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   day          244 non-null    int64  
 1   month        244 non-null    int64  
 2   year         244 non-null    int64  
 3   Temperature  244 non-null    int64  
 4    RH          244 non-null    int64  
 5    Ws          244 non-null    int64  
 6   Rain         244 non-null    float64
 7   FFMC         244 non-null    float64
 8   DMC          244 non-null    float64
 9   DC           244 non-null    float64
 10  ISI          244 non-null    float64
 11  BUI          244 non-null    float64
 12  FWI          244 non-null    object 
 13  Classes      243 non-null    object 
 14  Region       244 non-null    int64  
dtypes: float64(6), int64(7), object(2)
memory usage: 30.5+ KB


In [59]:
df.drop('FWI',axis=1)

day  month  year  Temperature   RH   Ws  Rain   FFMC   DMC    DC  ISI  \
0      1      6  2012           29   57   18    0.0  65.7   3.4   7.6  1.3   
1      2      6  2012           29   61   13    1.3  64.4   4.1   7.6  1.0   
2      3      6  2012           26   82   22   13.1  47.1   2.5   7.1  0.3   
3      4      6  2012           25   89   13    2.5  28.6   1.3   6.9  0.0   
4      5      6  2012           27   77   16    0.0  64.8   3.0  14.2  1.2   
..   ...    ...   ...          ...  ...  ...    ...   ...   ...   ...  ...   
241   26      9  2012           30   65   14    0.0  85.4  16.0  44.5  4.5   
242   27      9  2012           28   87   15    4.4  41.1   6.5   8.0  0.1   
243   28      9  2012           27   87   29    0.5  45.9   3.5   7.9  0.4   
244   29      9  2012           24   54   18    0.1  79.7   4.3  15.2  1.7   
245   30      9  2012           24   64   15    0.2  67.3   3.8  16.5  1.2   

      BUI Classes    Region  
0     3.4   notfire       0  
1     3.9   notfire       0  
2     2.7   notfire       0  
3     1.7   notfire       0  
4     3.9   notfire       0  
..    ...       ...     ...  
241  16.9      fire       1  
242   6.2   notfire       1  
243   3.4   notfire       1  
244   5.1   notfire       1  
245   4.8   notfire       1  

[244 rows x 14 columns]

In [60]:
df.describe()

day       month    year  Temperature          RH          Ws  \
count  244.000000  244.000000   244.0   244.000000  244.000000  244.000000   
mean    15.754098    7.500000  2012.0    32.172131   61.938525   15.504098   
std      8.825059    1.112961     0.0     3.633843   14.884200    2.810178   
min      1.000000    6.000000  2012.0    22.000000   21.000000    6.000000   
25%      8.000000    7.000000  2012.0    30.000000   52.000000   14.000000   
50%     16.000000    7.500000  2012.0    32.000000   63.000000   15.000000   
75%     23.000000    8.000000  2012.0    35.000000   73.250000   17.000000   
max     31.000000    9.000000  2012.0    42.000000   90.000000   29.000000   

            Rain         FFMC         DMC          DC         ISI         BUI  \
count  244.000000  244.000000  244.000000  244.000000  244.000000  244.000000   
mean     0.760656   77.887705   14.673361   49.288525    4.774180   16.664754   
std      1.999406   14.337571   12.368039   47.619363    4.175318   14.204824   
min      0.000000   28.600000    0.700000    6.900000    0.000000    1.100000   
25%      0.000000   72.075000    5.800000   13.275000    1.400000    6.000000   
50%      0.000000   83.500000   11.300000   33.100000    3.500000   12.250000   
75%      0.500000   88.300000   20.750000   68.150000    7.300000   22.525000   
max     16.800000   96.000000   65.900000  220.400000   19.000000   68.000000   

           Region  
count  244.000000  
mean     0.500000  
std      0.501028  
min      0.000000  
25%      0.000000  
50%      0.500000  
75%      1.000000  
max      1.000000

In [61]:
#defining a new dataframe as  dataset to perform logistic regression on it 
dataset=df

In [62]:
dataset.columns


Index(['day', 'month', 'year', 'Temperature', ' RH', ' Ws', 'Rain ', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes  ', 'Region'],
      dtype='object')

In [63]:
dataset = dataset.drop(['day', 'month', 'year'], axis=1)

In [64]:
dataset.head()

Temperature   RH   Ws  Rain   FFMC  DMC    DC  ISI  BUI  FWI Classes    \
0           29   57   18    0.0  65.7  3.4   7.6  1.3  3.4  0.5   notfire   
1           29   61   13    1.3  64.4  4.1   7.6  1.0  3.9  0.4   notfire   
2           26   82   22   13.1  47.1  2.5   7.1  0.3  2.7  0.1   notfire   
3           25   89   13    2.5  28.6  1.3   6.9  0.0  1.7    0   notfire   
4           27   77   16    0.0  64.8  3.0  14.2  1.2  3.9  0.5   notfire   

   Region  
0       0  
1       0  
2       0  
3       0  
4       0

In [90]:
dataset.shape

(244, 12)

In [114]:
dataset['Classes  '].unique()

array(['notfire', 'fire', nan], dtype=object)

In [117]:
dataset=dataset.dropna()

In [118]:
dataset.shape

(243, 12)

In [119]:
X=dataset.drop(['Classes  ', 'Region','FWI'],axis=1)
X.head()

Temperature   RH   Ws  Rain   FFMC  DMC    DC  ISI  BUI
0           29   57   18    0.0  65.7  3.4   7.6  1.3  3.4
1           29   61   13    1.3  64.4  4.1   7.6  1.0  3.9
2           26   82   22   13.1  47.1  2.5   7.1  0.3  2.7
3           25   89   13    2.5  28.6  1.3   6.9  0.0  1.7
4           27   77   16    0.0  64.8  3.0  14.2  1.2  3.9

In [120]:
y=dataset['Classes  ']
y.head()

0    notfire
1    notfire
2    notfire
3    notfire
4    notfire
Name: Classes  , dtype: object

In [121]:
X.shape,y.shape

((243, 9), (243,))

In [122]:
from sklearn.model_selection import train_test_split

In [123]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=10)

In [124]:
X_train.shape,y_train.shape

((162, 9), (162,))

In [125]:
X_test.shape

(81, 9)

In [126]:
####Standardize or feature scaling the datasets

In [127]:
from sklearn.preprocessing import StandardScaler

In [128]:
scaler=StandardScaler()
scaler

StandardScaler()

In [129]:
X_train

Temperature   RH   Ws  Rain   FFMC   DMC    DC   ISI   BUI
25            31   64   18    0.0  86.8  17.8  71.8   6.7  21.6
121           25   78   14    1.4  45.0   1.9   7.5   0.2   2.4
176           31   71   17    0.0  87.3  46.6  99.0   6.9  46.5
72            35   51   13    0.3  81.3  15.6  75.1   2.5  20.7
188           38   35   15    0.0  93.8  23.0  42.7  15.7  22.9
..           ...  ...  ...    ...   ...   ...   ...   ...   ...
64            34   69   13    0.0  85.0   8.2  19.8   4.0   8.2
15            29   89   13    0.7  36.1   1.7   7.6   0.0   2.2
231           33   26   13    0.0  93.9  21.2  59.2  14.2  22.4
127           30   64   14    0.0  79.4   5.2  15.4   2.2   5.6
9             28   79   12    0.0  73.2   9.5  46.3   1.3  12.6

[162 rows x 9 columns]

In [130]:
X_train.dtypes

Temperature      int64
 RH              int64
 Ws              int64
Rain           float64
FFMC           float64
DMC            float64
DC             float64
ISI            float64
BUI            float64
dtype: object

In [131]:
X_train=scaler.fit_transform(X_train)

In [132]:
X_test=scaler.transform(X_test)

In [133]:
X_train

array([[-0.301121  ,  0.06835876,  0.89673457, ...,  0.49028049,
         0.48086219,  0.38986031],
       [-1.98324518,  0.99672801, -0.58185068, ..., -0.86304801,
        -1.07139989, -1.0010797 ],
       [-0.301121  ,  0.53254338,  0.52708826, ...,  1.0627616 ,
         0.5286241 ,  2.19373563],
       ...,
       [ 0.25958707, -2.45150064, -0.95149699, ...,  0.22508704,
         2.27193383,  0.44781614],
       [-0.58147503,  0.06835876, -0.58185068, ..., -0.69677593,
        -0.59378078, -0.76925637],
       [-1.14218309,  1.0630401 , -1.3211433 , ..., -0.04642055,
        -0.80870938, -0.26214282]])

In [134]:
X_test

array([[-8.61829059e-01,  4.66231295e-01, -5.81850675e-01,
        -4.24064583e-01,  3.74594357e-01, -4.06694465e-01,
        -3.03195163e-01, -3.54971234e-01, -3.70810009e-01],
       [-8.61829059e-01, -9.26322582e-01,  1.26638088e+00,
        -4.24064583e-01,  7.58044470e-01, -2.28559462e-01,
        -3.17928133e-01,  1.05400512e+00, -2.76631780e-01],
       [ 1.10064916e+00, -4.62137956e-01,  1.57441947e-01,
        -4.24064583e-01,  7.77878096e-01,  8.14802699e-01,
         1.80888129e-01,  8.39076521e-01,  5.49238849e-01],
       [-1.70289115e+00,  1.19566428e+00,  2.00567350e+00,
         3.00789995e+00, -1.88643906e+00, -9.49582093e-01,
        -8.58838594e-01, -1.02363798e+00, -9.57612824e-01],
       [-8.61829059e-01,  1.12935219e+00, -5.81850675e-01,
         7.59371462e-01, -1.87982786e+00, -1.01744305e+00,
        -8.60943304e-01, -1.04751893e+00, -9.86590741e-01],
       [ 5.39941097e-01, -3.29513777e-01,  1.57441947e-01,
        -4.24064583e-01,  7.24988426e-01,  1.154107

# Model_training

In [135]:
from sklearn.linear_model import LogisticRegression

In [138]:
log_reg=LogisticRegression()
log_reg

LogisticRegression()

In [139]:
log_reg.fit(X_train,y_train)

LogisticRegression()

In [141]:
##print the coefficient and intercept

log_reg.coef_

array([[-0.07473927, -0.1698056 ,  0.05039843, -0.16128449, -2.58942849,
        -0.18902098,  0.21238807, -3.04375963, -0.47368771]])

In [142]:
log_reg.intercept_

array([-0.66605455])

In [143]:
##Prediction for the test data
log_reg_pred=regression.predict(X_test)

In [144]:
log_reg_pred

array(['fire', 'fire', 'fire', 'notfire', 'notfire', 'fire', 'notfire',
       'fire', 'fire', 'notfire', 'notfire', 'fire', 'fire', 'fire',
       'notfire', 'fire', 'notfire', 'fire', 'fire', 'notfire', 'notfire',
       'notfire', 'fire', 'notfire', 'notfire', 'fire', 'notfire',
       'notfire', 'notfire', 'notfire', 'fire', 'fire', 'fire', 'fire',
       'fire', 'notfire', 'notfire', 'notfire', 'fire', 'notfire', 'fire',
       'fire', 'fire', 'fire', 'fire', 'fire', 'notfire', 'fire',
       'notfire', 'notfire', 'fire', 'fire', 'fire', 'fire', 'notfire',
       'fire', 'fire', 'notfire', 'notfire', 'notfire', 'fire', 'notfire',
       'notfire', 'fire', 'fire', 'notfire', 'notfire', 'notfire', 'fire',
       'notfire', 'fire', 'fire', 'notfire', 'notfire', 'fire', 'fire',
       'fire', 'notfire', 'fire', 'notfire', 'fire'], dtype=object)

In [146]:
log_reg_pred.shape

(81,)

# Accuracy

In [148]:
from sklearn.metrics import accuracy_score

In [150]:
accuracy_score(y_test,log_reg_pred)

0.9506172839506173

# Confusion Matrix

In [161]:

from sklearn import metrics

In [162]:
cm = metrics.confusion_matrix(y_test,log_reg_pred)###to find confusion matrix

In [163]:
print(cm)

[[44  4]
 [ 0 33]]


In [165]:
true_positive=cm[0][0]
false_positive=cm[0][1]
false_negative=cm[1][0]
true_negative=cm[1][1]

Precision

In [167]:
Precision=true_positive/(true_positive+false_positive)
Precision

0.9166666666666666

Recall

In [169]:
Recall=true_positive/(true_positive+false_negative)
Recall

1.0

F1_score

In [172]:
F1_score=2*(Recall*Precision)/(Recall+Precision)
F1_score

0.9565217391304348

In [173]:
# Breaking down the formula for Accuracy
Accuracy = (true_positive + true_negative) / (true_positive +false_positive + false_negative + true_negative)
Accuracy

0.9506172839506173